# Generated by Django 5.2.8 on 2025-11-13 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=30)),
                ('Modelo', models.CharField(max_length=30)),
                ('Potencia', models.IntegerField()),
                ('Descricao', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=30)),
                ('Tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DadosSensor',
            fields=[
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DataHora', models.DateTimeField(auto_now=True)),
                ('Valor', models.FloatField()),
                ('MotorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensores.motor')),
                ('SensorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensores.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SensorMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MotorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensores.motor')),
                ('SensorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensores.sensor')),
            ],
        ),
    ]
