# Generated by Django 5.2.8 on 2025-11-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadossensor',
            name='Id',
        ),
        migrations.AddField(
            model_name='dadossensor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
