# Generated by Django 5.2.8 on 2025-11-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_remove_dadossensor_id_dadossensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadossensor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
